FROM atendai/evolution-api:v2.1.1

# Set environment variables
ENV NODE_ENV=production
ENV SERVER_PORT=8080
ENV DEL_INSTANCE=false
ENV DEL_TEMP_INSTANCES=true
ENV LANGUAGE=pt-BR
ENV LOG_LEVEL=ERROR
ENV STORE_CLEANING_INTERVAL=7200000
ENV STORE_MESSAGE_UP=true
ENV WEBHOOK_GLOBAL_ENABLED=true
ENV WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false

# Database configuration (disable database for free tier)
ENV DATABASE_ENABLED=false
ENV DATABASE_PROVIDER=none
ENV DATABASE_SAVE_DATA_INSTANCE=false
ENV DATABASE_SAVE_DATA_NEW_MESSAGE=false
ENV DATABASE_SAVE_MESSAGE_UPDATE=false
ENV DATABASE_SAVE_DATA_CONTACTS=false
ENV DATABASE_SAVE_DATA_CHATS=false

# Expose port (Render uses 8080 by default)
EXPOSE 8080

# Start the application (must have CMD for Render)
CMD ["node", "./dist/src/main.js"]
